from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List
from dataclasses import dataclass

@dataclass
class OrderResult:
    """Result of placing an order."""
    order_id: str          # Exchange's unique order identifier
    client_order_id: str   # Our own unique ID (clientOrderId)
    status: str            # "filled", "partial", "cancelled", "failed"
    filled_price: float    # Average fill price (0 if none)
    filled_volume: float   # Amount actually filled (in base currency)
    fee: float             # Total fee in quote currency
    raw_response: Any      # The full response from the exchange (for debugging)

class ExchangeClient(ABC):
    @abstractmethod
    async def get_balances(self) -> Dict[str, float]:
        """
        Returns a dictionary mapping asset names (e.g., "TONIRT", "USDT", "IRT") to balance.
        For base assets, use the common_symbol (e.g., "TONIRT").
        For quote currencies, use "USDT" or "IRT".
        """
        pass

    @abstractmethod
    async def place_market_order(self, symbol: str, side: str, amount: float, client_order_id: str) -> OrderResult:
        """
        Place a MARKET order (immediate execution).
        symbol: original symbol (e.g., "TONUSDT", "TON_IRT")
        side: "buy" or "sell"
        amount: amount in base currency (e.g., TON)
        client_order_id: a unique identifier generated by us (to track)
        Returns OrderResult.
        """
        pass

    @abstractmethod
    async def order_status(self, client_order_id: str) -> OrderResult:
        """Get current status of an order using our client_order_id."""
        pass

    @abstractmethod
    async def cancel_order(self, client_order_id: str) -> bool:
        """Cancel an order. Returns True if cancellation succeeded."""
        pass

    @abstractmethod
    async def withdraw(self, currency: str, amount: float, address: str, network: str) -> str:
        """Withdraw funds to an external address. Returns transaction ID."""
        pass